### ISSUE TITLE
[NamanShergill/Felix] Overlay Inspiration Cards: Part 1 - API call

### ISSUE THREAD

**Issue by deobald** [pariyatti/patta#10]
1. [ ] Querying the API returns Overlay Inspiration Cards
2. [ ] Overlay Inspiration Cards are de-serialized into model objects
3. [ ] Cache retrieved cards into the local database (as other cards do)
4. [ ] Use Platform-based Serif font akin to `Source Serif Pro` (Android) and whatever is nearest/equivalent on iOS

Step # 1. The sandbox API is available here: http://kosa-sandbox.pariyatti.org/api/v1/today.json ...a call to this API is already made within the app and the "cards" returned from the API are available as heterogeneous types in a flattened list. We're looking to add the cards with `type: "overlay_inspiration"`

**Comment by VarunBarad** [comment]
Closed by #30
