### ISSUE TITLE
[NamanShergill/Felix] Overlay Inspiration Cards: Part 2 - Display in the Today tab

### ISSUE THREAD

**Issue by deobald** [pariyatti/patta#4]
**This issue requires that [Overlay Inspiration Cards: Part 1 - API Call](https://github.com/pariyatti/patta/issues/10) is finished first.**

- [ ] Create a UI for Overlay Inspiration Cards (similar to Stacked Inspiration Cards and Pali Word Cards)
- [ ] User can bookmark an Overlay Inspiration Card
- [ ] Cards are pulled from the cache if there is no network access
- [ ] Refactor duplication between Overlay Inspiration Cards, Stacked Inspiration Cards, and Pali Word Cards

**Comment by VarunBarad** [comment]
Closed by #30
